version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - find docs/source -name "*.ipynb" -print0 | xargs -0 -I{} jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "{}"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
